### ISSUE TITLE
Implementation issue - found disconnected communities

### ISSUE THREAD

**Issue by jgbradley1** [puzzlef/leiden-lowmem-communities-openmp#2]
This is a great start at reducing the memory footprint of Leiden :). I ran several tests using the `europe_osm.mtx` graph with the `main` branch. When using 16 threads, I see a reduction in memory (~16.23 GB for default Leiden vs ~9.71 GB for the low memory version). However, there is an implementation problem - I am seeing disconnected communities in the final output of community memberships ☹️.

If you add a print statement to calculate and display the number of disconnected communities, similar to what you did in [your other repo](https://github.com/puzzlef/leiden-communities-openmp/blob/7cb7af76d739cc6b7f046ea24a15bea65ac78609/main.cxx#L65), you should be able to reproduce the problem.

I validated this issue using two approaches.
1. I modified the code to save off the community memberships to a file and read the results back in via python. I use [NetworkX.is_connected](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.is_connected.html) to check the connectedness of each community identified by Leiden.
2. I added calls to [your own function](https://github.com/puzzlef/leiden-lowmem-communities-openmp/blob/main/inc/properties.hxx#L379) to checks for disconnected communities and it reports a non-zero number.

The behavior I'm seeing is not reproducible in every experimental run of low memory gve leiden. The extra checks I performed above pass sometimes but also fail randomly. If I run the same experiment multiple times, I have found disconnected communities in ~2/5 times.

What is the best way set a random number generator seed to have reproducible output? (I see where the RNG is defined but it doesn’t appear to actually get used).

Any thoughts on where the bug might be? Happy to share more information if there's anything I can provide.

P.S. If possible, I recommend updating the mtx code to read in .mtx data and treat vertex ID's as 0-based [instead of 1-based](https://github.com/puzzlef/leiden-lowmem-communities-openmp/blob/main/inc/mtx.hxx#L239). I've noticed other [traditional graph tools](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.io.mmread.html) convert mtx files to 0-based vertex ID's as a standard. It reduces the likelihood of an off-by-1 error and allows for better integration with other tools in the OSS community.

**Comment by wolfram77** [comment]
One possibility I can think of is race conditions in the refinement phase. If this is the case, then suitable atomic operations need to be used (in the refinement phase at least). Another possibility is that the input graph is not exactly undirected - the parallel symmetrize may be incorrect.

@jgbradley1 Thanks for a detailed report on this. Do post an update here if you find the bug. I will keep looking as well.

**Comment by wolfram77** [comment]
I am seeing the disconnected communities on road networks and protien k-mer graphs (see [Logs](https://gist.github.com/wolfram77/d5b8e0b46952e1b58e8ad41faabe237f)).

![image](https://github.com/user-attachments/assets/2ec7bc8a-1e97-41aa-a183-a38c60b06a5e)

@jgbradley1 I will need some more time with this as I am going on vaction soon. Will take a look at it when back. See you later.

**Comment by wolfram77** [comment]
The fix works by ensuring that the aggregated graph is undirected. Since we are use low-memory scans for aggregate, the aggregated graph is not guaranteed to be undirected by default, even in the input graph is undirected.

Thanks @jgbradley1 for reporting the issue, I will be updating the report in some time. Here are the current [logs](https://gist.github.com/wolfram77/a6875aeedbec3fb79df2990132804196).

**Comment by jgbradley1** [comment]
Great find @wolfram77 and thanks for fixing!

Since the algorithm is non-deterministic in nature, is there a way to set a seed value such that repeating the algorithm run on the same data with the same seed will always result in the same community assignments per vertex?

**Comment by wolfram77** [comment]
@jgbradley1 I could build a solution with you on this. I have just submitted my PhD summary and looking to fork into an awesome place to join and contribute with commitment. 😉
